name: Dependency Jobs
on: 
  - push
  - workflow_dispatch
  

jobs:
  job1:
    needs: job2 
    runs-on: ubuntu-latest
    steps:
      - run: echo job1

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo job2

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo job3

  job4:
    runs-on: ubuntu-latest
    steps:
      - run: echo job4

  job5:
    needs: [job3,job4]
    runs-on: ubuntu-latest
    steps:
      - run: echo job5

  job6:
    runs-on: ubuntu-latest
    steps:
      - run: echo job6

  job7:
    runs-on: ubuntu-latest
    steps:
      - run: echo job7

  job8:
    needs: job5 
    runs-on: ubuntu-latest
    steps:
      - run: echo job8


      